import type { ManagedLoan } from "@/lib/loans";

export async function downloadLoanAgreement(loan: ManagedLoan) {
  const { default: jsPDF } = await import("jspdf");
  const pdf = new jsPDF();

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.text("PanAfrika Bank Loan Agreement", 20, 24);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.text(`Loan ID: ${loan.id}`, 20, 38);
  pdf.text(`Borrower: Adaobi Chukwu`, 20, 46);
  pdf.text(`Product: ${loan.type}`, 20, 54);
  pdf.text(`Disbursed Amount: ${loan.currency} ${loan.disbursedAmount.toLocaleString()}`, 20, 62);
  pdf.text(`Interest Rate: ${loan.interestRate}%`, 20, 70);
  pdf.text(`Tenor: ${loan.tenorMonths} months`, 20, 78);
  pdf.text(`Monthly Repayment: ${loan.currency} ${Math.round(loan.monthlyRepayment).toLocaleString()}`, 20, 86);
  pdf.text(`Status: ${loan.status}`, 20, 94);

  pdf.setFont("helvetica", "bold");
  pdf.text("Key Terms", 20, 110);
  pdf.setFont("helvetica", "normal");
  pdf.text(
    "The borrower undertakes to repay the facility on the agreed due dates. PanAfrika Bank reserves the right to debit the designated repayment account for monthly installments and applicable charges.",
    20,
    120,
    { maxWidth: 170 },
  );

  pdf.text(
    "This document is generated by the PanAfrika core banking emulator for portfolio demonstration purposes only and does not represent a real credit contract.",
    20,
    148,
    { maxWidth: 170 },
  );

  pdf.save(`${loan.id}-agreement.pdf`);
}
